#! /bin/sh
########################################################################
#
#  ISABEL: A group collaboration tool for the Internet
#  Copyright (C) 2012 Agora System S.A.
#  
#  This file is part of Isabel.
#  
#  Isabel is free software: you can redistribute it and/or modify
#  it under the terms of the Affero GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Isabel is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  Affero GNU General Public License for more details.
# 
#  You should have received a copy of the Affero GNU General Public License
#  along with Isabel.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

#-----------------------------------------------------
# isabel directory.
#-----------------------------------------------------
if [ -z "$ISABEL_DIR" ] ; then
  ISABEL_DIR=/usr/local/isabel
  export ISABEL_DIR
fi

#-----------------------------------------------------
# isabel common code
#-----------------------------------------------------
. $ISABEL_DIR/bin/isabel.common.sh

#-----------------------------------------------------
# isabel environment variables
#-----------------------------------------------------
. $ISABEL_DIR/bin/isabel.environ.sh

#-----------------------------------------------------
# Some log messages
#-----------------------------------------------------
WriteLogMsg "Launching isabel ($ISABEL_VERSION-$ISABEL_RELEASE)"

#-----------------------------------------------------
# Checking ISABEL requirements
#-----------------------------------------------------
. $ISABEL_DIR/bin/isabel.requires.sh

#-----------------------------------------------------
# Cleanup
#-----------------------------------------------------

#-----------------------------------------------------
# Logs configuration.
#-----------------------------------------------------
if [ ! -f $ISABEL_CONFIG_DIR/logging.properties ] ; then
   cp $ISABEL_DIR/lib/logging.properties $ISABEL_CONFIG_DIR/.
fi

#-----------------------------------------------------
# Invoke remote
#-----------------------------------------------------

jarmenu=$ISABEL_DIR/libexec/isabel_menu.jar
jarlib=$ISABEL_DIR/libexec/isabel_lib.jar

WriteLogMsg "Launching Isabel Menu Launcher."

_menulogfn=$(CreateLogFilename menu)

WriteLogMsg "$_menulogfn"

WriteLogMsg " $ISAJAVA -cp $jarmenu:$jarlib:$ISABEL_DIR/lib:$ISABEL_DIR/doc \
         -Djava.util.logging.config.file=$ISABEL_CONFIG_DIR/logging.properties \
         -Dxlim.dir=$ISABEL_DIR/lib  \
         -Dxlim.user.dir=$ISABEL_CONFIG_DIR \
         -Disabel.dir=$ISABEL_DIR \
         -Disabel.profiles.dir=$ISABEL_PROFILES_DIR \
         -Disabel.sessions.dir=$ISABEL_SESSIONS_DIR \
         -Disabel.user.dir=$ISABEL_USER_DIR \
         -Disabel.config.dir=$ISABEL_CONFIG_DIR \
          isabel.menulauncher.IsabelMenu $* > $_menulogfn 2>&1 &"

$ISAJAVA -cp $jarmenu:$jarlib:$ISABEL_DIR/lib \
         -Djava.util.logging.config.file=$ISABEL_CONFIG_DIR/logging.properties \
          isabel.menulauncher.IsabelMenu $* > $_menulogfn 2>&1 &


#-----------------------------------------------------
# Cleanup
#-----------------------------------------------------


exit 0

