include $(PROJECT_ROOT_DIR)/Makefile.head

SUBDIRS.PRE=activity control
SUBDIRS.POST=

rmdist:
	@echo "   ...borrando $(DISTRIB_DIR)"
	rm -rf $(DISTRIB_DIR)

include $(PROJECT_ROOT_DIR)/Makefile.tail
