include $(PROJECT_ROOT_DIR)/Makefile.head

distrib::
	@echo "audio_test.mp3 --> $(DISTRIB_DIR)/isabelcore/test/"
	@mkdir -p $(DISTRIB_DIR)/isabelcore/test
	@cp -f audio_test.mp3 $(DISTRIB_DIR)/isabelcore/test/

include $(PROJECT_ROOT_DIR)/Makefile.tail
