USE.LIBS= ICF2-NON-THREADED
include $(PROJECT_ROOT_DIR)/Makefile.head

TARGET= sdlsounddevice.o

SRC= sdlsounddevice.cpp

OBJ=$(SRC:%.cpp=$(OBJDIR)/%.o)


distrib::

clean::
	rm -f $(OBJ)

cleanall:: clean

include $(PROJECT_ROOT_DIR)/Makefile.tail
