//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}unicast" minOccurs="0"/>
 *         &lt;element ref="{}mcu" minOccurs="0"/>
 *         &lt;element ref="{}multicast" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unicast",
    "mcu",
    "multicast"
})
@XmlRootElement(name = "CONNECTION-MODE")
public class CONNECTIONMODE {

    protected Unicast unicast;
    protected Mcu mcu;
    protected Multicast multicast;

    /**
     * Gets the value of the unicast property.
     * 
     * @return
     *     possible object is
     *     {@link Unicast }
     *     
     */
    public Unicast getUnicast() {
        return unicast;
    }

    /**
     * Sets the value of the unicast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unicast }
     *     
     */
    public void setUnicast(Unicast value) {
        this.unicast = value;
    }

    /**
     * Gets the value of the mcu property.
     * 
     * @return
     *     possible object is
     *     {@link Mcu }
     *     
     */
    public Mcu getMcu() {
        return mcu;
    }

    /**
     * Sets the value of the mcu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mcu }
     *     
     */
    public void setMcu(Mcu value) {
        this.mcu = value;
    }

    /**
     * Gets the value of the multicast property.
     * 
     * @return
     *     possible object is
     *     {@link Multicast }
     *     
     */
    public Multicast getMulticast() {
        return multicast;
    }

    /**
     * Sets the value of the multicast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multicast }
     *     
     */
    public void setMulticast(Multicast value) {
        this.multicast = value;
    }

}
