//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for edl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="edl">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element ref="{}SESSION" minOccurs="0"/>
 *         &lt;element ref="{}site-description" minOccurs="0"/>
 *         &lt;element ref="{}TEMPLATE" minOccurs="0"/>
 *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "edl", propOrder = {
    "version",
    "session",
    "siteDescription",
    "template",
    "url",
    "any"
})
public class Edl {

    @XmlElement(name = "VERSION", required = true, defaultValue = "1.8")
    protected BigDecimal version = new BigDecimal("1.8");
    @XmlElement(name = "SESSION")
    protected SESSION session;
    @XmlElement(name = "site-description")
    protected SiteDescription siteDescription;
    @XmlElement(name = "TEMPLATE")
    protected TEMPLATE template;
    @XmlElement(name = "URL", required = true, defaultValue = "")
    @XmlSchemaType(name = "anyURI")
    protected String url="";
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVERSION(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link SESSION }
     *     
     */
    public SESSION getSESSION() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link SESSION }
     *     
     */
    public void setSESSION(SESSION value) {
        this.session = value;
    }

    /**
     * Gets the value of the siteDescription property.
     * 
     * @return
     *     possible object is
     *     {@link SiteDescription }
     *     
     */
    public SiteDescription getSiteDescription() {
        return siteDescription;
    }

    /**
     * Sets the value of the siteDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteDescription }
     *     
     */
    public void setSiteDescription(SiteDescription value) {
        this.siteDescription = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link TEMPLATE }
     *     
     */
    public TEMPLATE getTEMPLATE() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEMPLATE }
     *     
     */
    public void setTEMPLATE(TEMPLATE value) {
        this.template = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }
    
    
    /**
     * Method to add a site, if the site exist, it is replaced by the new one
     * @param newsite the site to be added
     */
    public void addSITE(SITE newsite){
    	String id = newsite.getID();
    	SiteDescription desc = null;
    	desc = getSiteDescription();
    	if(desc == null)
    	{
    		//siteDescription not defined I define it
    		desc = new SiteDescription();
    	}
    	if(desc.getSITE(id)!=null)
    	{
    		//I delete the old one before adding the new one
    		List<SITE> milista = desc.getSITE();
    		for(int i =0; i< milista.size(); i++){
    			if(milista.get(i).getID().equals(id))
    				milista.remove(i);
    		}
    	}
    	desc.getSITE().add(newsite);
    	setSiteDescription(desc);
    }

}
