//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ipsec_exchangemode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ipsec_exchangemode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="main"/>
 *     &lt;enumeration value="aggressive"/>
 *     &lt;enumeration value="base"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ipsec_exchangemode")
@XmlEnum
public enum IpsecExchangemode {

    @XmlEnumValue("main")
    MAIN("main"),
    @XmlEnumValue("aggressive")
    AGGRESSIVE("aggressive"),
    @XmlEnumValue("base")
    BASE("base");
    private final String value;

    IpsecExchangemode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IpsecExchangemode fromValue(String v) {
        for (IpsecExchangemode c: IpsecExchangemode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
