//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DIRECTION" type="{}ipsec_direction"/>
 *         &lt;element name="ACTION" type="{}ipsec_action"/>
 *         &lt;element name="IKEAssociation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MinLifetimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="MinLifetimeKilobytes" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="ExchangeMode" type="{}ipsec_exchangemode"/>
 *                   &lt;element name="DhGroup" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IPsecAssociation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MinLifetimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="MinLifetimeKilobytes" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="UsePfs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="UseIPComp" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="Protocol" type="{}ipsec_protocol"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "direction",
    "action",
    "ikeAssociation",
    "iPsecAssociation"
})
@XmlRootElement(name = "IPSEC_CONF")
public class IPSECCONF {

    @XmlElement(name = "DIRECTION", required = true)
    protected IpsecDirection direction;
    @XmlElement(name = "ACTION", required = true)
    protected IpsecAction action;
    @XmlElement(name = "IKEAssociation", required = true)
    protected IPSECCONF.IKEAssociation ikeAssociation;
    @XmlElement(name = "IPsecAssociation", required = true)
    protected IPSECCONF.IPsecAssociation iPsecAssociation;

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link IpsecDirection }
     *     
     */
    public IpsecDirection getDIRECTION() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpsecDirection }
     *     
     */
    public void setDIRECTION(IpsecDirection value) {
        this.direction = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link IpsecAction }
     *     
     */
    public IpsecAction getACTION() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpsecAction }
     *     
     */
    public void setACTION(IpsecAction value) {
        this.action = value;
    }

    /**
     * Gets the value of the ikeAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link IPSECCONF.IKEAssociation }
     *     
     */
    public IPSECCONF.IKEAssociation getIKEAssociation() {
        return ikeAssociation;
    }

    /**
     * Sets the value of the ikeAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPSECCONF.IKEAssociation }
     *     
     */
    public void setIKEAssociation(IPSECCONF.IKEAssociation value) {
        this.ikeAssociation = value;
    }

    /**
     * Gets the value of the iPsecAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link IPSECCONF.IPsecAssociation }
     *     
     */
    public IPSECCONF.IPsecAssociation getIPsecAssociation() {
        return iPsecAssociation;
    }

    /**
     * Sets the value of the iPsecAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPSECCONF.IPsecAssociation }
     *     
     */
    public void setIPsecAssociation(IPSECCONF.IPsecAssociation value) {
        this.iPsecAssociation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MinLifetimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="MinLifetimeKilobytes" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="ExchangeMode" type="{}ipsec_exchangemode"/>
     *         &lt;element name="DhGroup" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minLifetimeSeconds",
        "minLifetimeKilobytes",
        "exchangeMode",
        "dhGroup"
    })
    public static class IKEAssociation {

        @XmlElement(name = "MinLifetimeSeconds", required = true)
        protected BigDecimal minLifetimeSeconds;
        @XmlElement(name = "MinLifetimeKilobytes")
        protected BigDecimal minLifetimeKilobytes;
        @XmlElement(name = "ExchangeMode", required = true)
        protected IpsecExchangemode exchangeMode;
        @XmlElement(name = "DhGroup", required = true)
        protected BigDecimal dhGroup;

        /**
         * Gets the value of the minLifetimeSeconds property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMinLifetimeSeconds() {
            return minLifetimeSeconds;
        }

        /**
         * Sets the value of the minLifetimeSeconds property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMinLifetimeSeconds(BigDecimal value) {
            this.minLifetimeSeconds = value;
        }

        /**
         * Gets the value of the minLifetimeKilobytes property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMinLifetimeKilobytes() {
            return minLifetimeKilobytes;
        }

        /**
         * Sets the value of the minLifetimeKilobytes property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMinLifetimeKilobytes(BigDecimal value) {
            this.minLifetimeKilobytes = value;
        }

        /**
         * Gets the value of the exchangeMode property.
         * 
         * @return
         *     possible object is
         *     {@link IpsecExchangemode }
         *     
         */
        public IpsecExchangemode getExchangeMode() {
            return exchangeMode;
        }

        /**
         * Sets the value of the exchangeMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link IpsecExchangemode }
         *     
         */
        public void setExchangeMode(IpsecExchangemode value) {
            this.exchangeMode = value;
        }

        /**
         * Gets the value of the dhGroup property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDhGroup() {
            return dhGroup;
        }

        /**
         * Sets the value of the dhGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDhGroup(BigDecimal value) {
            this.dhGroup = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MinLifetimeSeconds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="MinLifetimeKilobytes" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="UsePfs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="UseIPComp" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="Protocol" type="{}ipsec_protocol"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minLifetimeSeconds",
        "minLifetimeKilobytes",
        "usePfs",
        "useIPComp",
        "protocol"
    })
    public static class IPsecAssociation {

        @XmlElement(name = "MinLifetimeSeconds", required = true)
        protected BigDecimal minLifetimeSeconds;
        @XmlElement(name = "MinLifetimeKilobytes")
        protected BigDecimal minLifetimeKilobytes;
        @XmlElement(name = "UsePfs")
        protected BigDecimal usePfs;
        @XmlElement(name = "UseIPComp")
        protected Boolean useIPComp;
        @XmlElement(name = "Protocol", required = true)
        protected IpsecProtocol protocol;

        /**
         * Gets the value of the minLifetimeSeconds property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMinLifetimeSeconds() {
            return minLifetimeSeconds;
        }

        /**
         * Sets the value of the minLifetimeSeconds property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMinLifetimeSeconds(BigDecimal value) {
            this.minLifetimeSeconds = value;
        }

        /**
         * Gets the value of the minLifetimeKilobytes property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMinLifetimeKilobytes() {
            return minLifetimeKilobytes;
        }

        /**
         * Sets the value of the minLifetimeKilobytes property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMinLifetimeKilobytes(BigDecimal value) {
            this.minLifetimeKilobytes = value;
        }

        /**
         * Gets the value of the usePfs property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUsePfs() {
            return usePfs;
        }

        /**
         * Sets the value of the usePfs property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUsePfs(BigDecimal value) {
            this.usePfs = value;
        }

        /**
         * Gets the value of the useIPComp property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isUseIPComp() {
            return useIPComp;
        }

        /**
         * Sets the value of the useIPComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUseIPComp(Boolean value) {
            this.useIPComp = value;
        }

        /**
         * Gets the value of the protocol property.
         * 
         * @return
         *     possible object is
         *     {@link IpsecProtocol }
         *     
         */
        public IpsecProtocol getProtocol() {
            return protocol;
        }

        /**
         * Sets the value of the protocol property.
         * 
         * @param value
         *     allowed object is
         *     {@link IpsecProtocol }
         *     
         */
        public void setProtocol(IpsecProtocol value) {
            this.protocol = value;
        }

    }

}
