//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ipsec_protocol.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ipsec_protocol">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ah"/>
 *     &lt;enumeration value="esp"/>
 *     &lt;enumeration value="ah_esp"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ipsec_protocol")
@XmlEnum
public enum IpsecProtocol {

    @XmlEnumValue("ah")
    AH("ah"),
    @XmlEnumValue("esp")
    ESP("esp"),
    @XmlEnumValue("ah_esp")
    AH_ESP("ah_esp");
    private final String value;

    IpsecProtocol(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IpsecProtocol fromValue(String v) {
        for (IpsecProtocol c: IpsecProtocol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
