//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}ISDN-caller"/>
 *         &lt;element ref="{}ISDN-called"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isdnCaller",
    "isdnCalled"
})
@XmlRootElement(name = "ISDN-parameters")
public class ISDNParameters {

    @XmlElement(name = "ISDN-caller")
    protected ISDNCaller isdnCaller;
    @XmlElement(name = "ISDN-called")
    protected ISDNCalled isdnCalled;

    /**
     * Gets the value of the isdnCaller property.
     * 
     * @return
     *     possible object is
     *     {@link ISDNCaller }
     *     
     */
    public ISDNCaller getISDNCaller() {
        return isdnCaller;
    }

    /**
     * Sets the value of the isdnCaller property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISDNCaller }
     *     
     */
    public void setISDNCaller(ISDNCaller value) {
        this.isdnCaller = value;
    }

    /**
     * Gets the value of the isdnCalled property.
     * 
     * @return
     *     possible object is
     *     {@link ISDNCalled }
     *     
     */
    public ISDNCalled getISDNCalled() {
        return isdnCalled;
    }

    /**
     * Sets the value of the isdnCalled property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISDNCalled }
     *     
     */
    public void setISDNCalled(ISDNCalled value) {
        this.isdnCalled = value;
    }

    
    /**
	 * Method to know if the isdn is the caller
	 * @return
	 */
	public boolean isCaller()
	{
		return this.getISDNCaller()!=null;		
	}
	
	
	/**
	 * Method to know if the isdn is the called
	 * @return
	 */
	public boolean isCalled()
	{
		return this.getISDNCalled()!=null;		
	}
	
	
	/**
   	* Gets ISDN channels.Returns -1 if empty or not found.
   	**/
    public int getISDNChannels(){
    	if(isCalled())
    		return getISDNCalled().getISDNCHANNELS();
    	if(isCaller())
    		return getISDNCaller().getISDNCHANNELS();
    	return -1;
    }
       
}
