//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ISDN_CHANNELS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ISDN_PHONE_MSN" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="ISDN_PHONE_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isdnchannels",
    "isdnphonemsn",
    "isdnphonenumber"
})
@XmlRootElement(name = "ISDN-caller")
public class ISDNCaller {

    @XmlElement(name = "ISDN_CHANNELS")
    protected int isdnchannels;
    @XmlElement(name = "ISDN_PHONE_MSN", required = true)
    protected List<String> isdnphonemsn;
    @XmlElement(name = "ISDN_PHONE_NUMBER", required = true)
    protected List<String> isdnphonenumber;

    /**
     * Gets the value of the isdnchannels property.
     * 
     */
    public int getISDNCHANNELS() {
        return isdnchannels;
    }

    /**
     * Sets the value of the isdnchannels property.
     * 
     */
    public void setISDNCHANNELS(int value) {
        this.isdnchannels = value;
    }

    /**
     * Gets the value of the isdnphonemsn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isdnphonemsn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getISDNPHONEMSN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getISDNPHONEMSN() {
        if (isdnphonemsn == null) {
            isdnphonemsn = new ArrayList<String>();
        }
        return this.isdnphonemsn;
    }

    /**
     * Gets the value of the isdnphonenumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isdnphonenumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getISDNPHONENUMBER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getISDNPHONENUMBER() {
        if (isdnphonenumber == null) {
            isdnphonenumber = new ArrayList<String>();
        }
        return this.isdnphonenumber;
    }

}
