//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DEFAULT_CTRL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="APP_SHARING_CTRL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AUDIO_CTRL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DATA_CTRL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VIDEO_CTRL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defaultctrl",
    "appsharingctrl",
    "audioctrl",
    "datactrl",
    "videoctrl"
})
@XmlRootElement(name = "media-control")
public class MediaControl {

    @XmlElement(name = "DEFAULT_CTRL")
    protected String defaultctrl;
    @XmlElement(name = "APP_SHARING_CTRL")
    protected String appsharingctrl;
    @XmlElement(name = "AUDIO_CTRL")
    protected String audioctrl;
    @XmlElement(name = "DATA_CTRL")
    protected String datactrl;
    @XmlElement(name = "VIDEO_CTRL")
    protected String videoctrl;

    /**
     * Gets the value of the defaultctrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEFAULTCTRL() {
        return defaultctrl;
    }

    /**
     * Sets the value of the defaultctrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEFAULTCTRL(String value) {
        this.defaultctrl = value;
    }

    /**
     * Gets the value of the appsharingctrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPSHARINGCTRL() {
        return appsharingctrl;
    }

    /**
     * Sets the value of the appsharingctrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPSHARINGCTRL(String value) {
        this.appsharingctrl = value;
    }

    /**
     * Gets the value of the audioctrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUDIOCTRL() {
        return audioctrl;
    }

    /**
     * Sets the value of the audioctrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUDIOCTRL(String value) {
        this.audioctrl = value;
    }

    /**
     * Gets the value of the datactrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATACTRL() {
        return datactrl;
    }

    /**
     * Sets the value of the datactrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATACTRL(String value) {
        this.datactrl = value;
    }

    /**
     * Gets the value of the videoctrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVIDEOCTRL() {
        return videoctrl;
    }

    /**
     * Sets the value of the videoctrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVIDEOCTRL(String value) {
        this.videoctrl = value;
    }

}
