//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MCAST_ROOT" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MCAST_TTL" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="MCAST_MODE" type="{}mcast-mode-type" minOccurs="0"/>
 *         &lt;element name="MCAST_AUDIO_GROUP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MCAST_VIDEO_GROUP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MCAST_FTP_GROUP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MCAST_POINTER_GROUP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MCAST_VUMETER_GROUP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MCAST_APPSH_GROUP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mcastroot",
    "mcastttl",
    "mcastmode",
    "mcastaudiogroup",
    "mcastvideogroup",
    "mcastftpgroup",
    "mcastpointergroup",
    "mcastvumetergroup",
    "mcastappshgroup"
})
@XmlRootElement(name = "multicast-parameters")
public class MulticastParameters {

    @XmlElement(name = "MCAST_ROOT")
    protected String mcastroot;
    @XmlElement(name = "MCAST_TTL")
    protected Byte mcastttl;
    @XmlElement(name = "MCAST_MODE")
    protected McastModeType mcastmode;
    @XmlElement(name = "MCAST_AUDIO_GROUP")
    protected Object mcastaudiogroup;
    @XmlElement(name = "MCAST_VIDEO_GROUP")
    protected Object mcastvideogroup;
    @XmlElement(name = "MCAST_FTP_GROUP")
    protected Object mcastftpgroup;
    @XmlElement(name = "MCAST_POINTER_GROUP")
    protected Object mcastpointergroup;
    @XmlElement(name = "MCAST_VUMETER_GROUP")
    protected Object mcastvumetergroup;
    @XmlElement(name = "MCAST_APPSH_GROUP")
    protected Object mcastappshgroup;

    /**
     * Gets the value of the mcastroot property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public String getMCASTROOT() {
        return mcastroot;
    }

    /**
     * Sets the value of the mcastroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMCASTROOT(String value) {
        this.mcastroot = value;
    }

    /**
     * Gets the value of the mcastttl property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMCASTTTL() {
        return mcastttl;
    }

    /**
     * Sets the value of the mcastttl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMCASTTTL(Byte value) {
        this.mcastttl = value;
    }

    /**
     * Gets the value of the mcastmode property.
     * 
     * @return
     *     possible object is
     *     {@link McastModeType }
     *     
     */
    public McastModeType getMCASTMODE() {
        return mcastmode;
    }

    /**
     * Sets the value of the mcastmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link McastModeType }
     *     
     */
    public void setMCASTMODE(McastModeType value) {
        this.mcastmode = value;
    }

    /**
     * Gets the value of the mcastaudiogroup property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMCASTAUDIOGROUP() {
        return mcastaudiogroup;
    }

    /**
     * Sets the value of the mcastaudiogroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMCASTAUDIOGROUP(Object value) {
        this.mcastaudiogroup = value;
    }

    /**
     * Gets the value of the mcastvideogroup property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMCASTVIDEOGROUP() {
        return mcastvideogroup;
    }

    /**
     * Sets the value of the mcastvideogroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMCASTVIDEOGROUP(Object value) {
        this.mcastvideogroup = value;
    }

    /**
     * Gets the value of the mcastftpgroup property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMCASTFTPGROUP() {
        return mcastftpgroup;
    }

    /**
     * Sets the value of the mcastftpgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMCASTFTPGROUP(Object value) {
        this.mcastftpgroup = value;
    }

    /**
     * Gets the value of the mcastpointergroup property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMCASTPOINTERGROUP() {
        return mcastpointergroup;
    }

    /**
     * Sets the value of the mcastpointergroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMCASTPOINTERGROUP(Object value) {
        this.mcastpointergroup = value;
    }

    /**
     * Gets the value of the mcastvumetergroup property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMCASTVUMETERGROUP() {
        return mcastvumetergroup;
    }

    /**
     * Sets the value of the mcastvumetergroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMCASTVUMETERGROUP(Object value) {
        this.mcastvumetergroup = value;
    }

    /**
     * Gets the value of the mcastappshgroup property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMCASTAPPSHGROUP() {
        return mcastappshgroup;
    }

    /**
     * Sets the value of the mcastappshgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMCASTAPPSHGROUP(Object value) {
        this.mcastappshgroup = value;
    }

}
