//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Ethernet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{}ISDN"/>
 *         &lt;element ref="{}modem"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ethernet",
    "isdn",
    "modem"
})
@XmlRootElement(name = "NETWORK-ACCESS")
public class NETWORKACCESS {

    @XmlElement(name = "Ethernet")
    protected Boolean ethernet;
    @XmlElement(name = "ISDN")
    protected ISDN isdn;
    protected Modem modem;

    /**
     * Gets the value of the ethernet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEthernet() {
        return ethernet;
    }

    /**
     * Sets the value of the ethernet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEthernet(Boolean value) {
        this.ethernet = value;
    }

    /**
     * Gets the value of the isdn property.
     * 
     * @return
     *     possible object is
     *     {@link ISDN }
     *     
     */
    public ISDN getISDN() {
        return isdn;
    }

    /**
     * Sets the value of the isdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISDN }
     *     
     */
    public void setISDN(ISDN value) {
        this.isdn = value;
    }

    /**
     * Gets the value of the modem property.
     * 
     * @return
     *     possible object is
     *     {@link Modem }
     *     
     */
    public Modem getModem() {
        return modem;
    }

    /**
     * Sets the value of the modem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modem }
     *     
     */
    public void setModem(Modem value) {
        this.modem = value;
    }

}
