//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the isabel.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EDL_QNAME = new QName("", "EDL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: isabel.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProtectionType.Hamming }
     * 
     */
    public ProtectionType.Hamming createProtectionTypeHamming() {
        return new ProtectionType.Hamming();
    }

    /**
     * Create an instance of {@link IPSECCONF.IKEAssociation }
     * 
     */
    public IPSECCONF.IKEAssociation createIPSECCONFIKEAssociation() {
        return new IPSECCONF.IKEAssociation();
    }

    /**
     * Create an instance of {@link SITEADDITIONALPARAMS }
     * 
     */
    public SITEADDITIONALPARAMS createSITEADDITIONALPARAMS() {
        return new SITEADDITIONALPARAMS();
    }

    /**
     * Create an instance of {@link IPSECCONF }
     * 
     */
    public IPSECCONF createIPSECCONF() {
        return new IPSECCONF();
    }

    /**
     * Create an instance of {@link ProtectionType }
     * 
     */
    public ProtectionType createProtectionType() {
        return new ProtectionType();
    }

    /**
     * Create an instance of {@link ISDNParameters }
     * 
     */
    public ISDNParameters createISDNParameters() {
        return new ISDNParameters();
    }

    
    /**
     * Create an instance of {@link Edl }
     * 
     */
    public Edl createEdl() {
        return new Edl();
    }

    /**
     * Create an instance of {@link SERVICE }
     * 
     */
    public SERVICE createSERVICE() {
        return new SERVICE();
    }

    /**
     * Create an instance of {@link SiteIdentification }
     * 
     */
    public SiteIdentification createSiteIdentification() {
        return new SiteIdentification();
    }

    /**
     * Create an instance of {@link MulticastParameters }
     * 
     */
    public MulticastParameters createMulticastParameters() {
        return new MulticastParameters();
    }

    /**
     * Create an instance of {@link Upanddownbandwidth }
     * 
     */
    public Upanddownbandwidth createUpanddownbandwidth() {
        return new Upanddownbandwidth();
    }

    /**
     * Create an instance of {@link SessionInfo }
     * 
     */
    public SessionInfo createSessionInfo() {
        return new SessionInfo();
    }

    /**
     * Create an instance of {@link SiteDescription }
     * 
     */
    public SiteDescription createSiteDescription() {
        return new SiteDescription();
    }

    /**
     * Create an instance of {@link SESSIONADDITIONALPARAMS }
     * 
     */
    public SESSIONADDITIONALPARAMS createSESSIONADDITIONALPARAMS() {
        return new SESSIONADDITIONALPARAMS();
    }

    /**
     * Create an instance of {@link SITE }
     * 
     */
    public SITE createSITE() {
        return new SITE();
    }

    /**
     * Create an instance of {@link Modem }
     * 
     */
    public Modem createModem() {
        return new Modem();
    }

    /**
     * Create an instance of {@link CONNECTIONMODE }
     * 
     */
    public CONNECTIONMODE createCONNECTIONMODE() {
        return new CONNECTIONMODE();
    }

    /**
     * Create an instance of {@link TEMPLATE }
     * 
     */
    public TEMPLATE createTEMPLATE() {
        return new TEMPLATE();
    }

    /**
     * Create an instance of {@link Mcu }
     * 
     */
    public Mcu createMcu() {
        return new Mcu();
    }

    /**
     * Create an instance of {@link IPSECCONF.IPsecAssociation }
     * 
     */
    public IPSECCONF.IPsecAssociation createIPSECCONFIPsecAssociation() {
        return new IPSECCONF.IPsecAssociation();
    }

    /**
     * Create an instance of {@link SiteIdentification.ADMINISTRATIVEINFORMATION }
     * 
     */
    public SiteIdentification.ADMINISTRATIVEINFORMATION createSiteIdentificationADMINISTRATIVEINFORMATION() {
        return new SiteIdentification.ADMINISTRATIVEINFORMATION();
    }

    /**
     * Create an instance of {@link SESSION }
     * 
     */
    public SESSION createSESSION() {
        return new SESSION();
    }

    /**
     * Create an instance of {@link ProtectionType.Parity }
     * 
     */
    public ProtectionType.Parity createProtectionTypeParity() {
        return new ProtectionType.Parity();
    }

    /**
     * Create an instance of {@link ISDNCaller }
     * 
     */
    public ISDNCaller createISDNCaller() {
        return new ISDNCaller();
    }

    /**
     * Create an instance of {@link NETWORKACCESS }
     * 
     */
    public NETWORKACCESS createNETWORKACCESS() {
        return new NETWORKACCESS();
    }

    /**
     * Create an instance of {@link Multicast }
     * 
     */
    public Multicast createMulticast() {
        return new Multicast();
    }

    /**
     * Create an instance of {@link PersonalInformation }
     * 
     */
    public PersonalInformation createPersonalInformation() {
        return new PersonalInformation();
    }

    /**
     * Create an instance of {@link ConnectionParameters }
     * 
     */
    public ConnectionParameters createConnectionParameters() {
        return new ConnectionParameters();
    }

    /**
     * Create an instance of {@link ModemElement }
     * 
     */
    public ModemElement createModemElement() {
        return new ModemElement();
    }

    /**
     * Create an instance of {@link ISDNCalled }
     * 
     */
    public ISDNCalled createISDNCalled() {
        return new ISDNCalled();
    }

    /**
     * Create an instance of {@link ISDN }
     * 
     */
    public ISDN createISDN() {
        return new ISDN();
    }

    /**
     * Create an instance of {@link SiteIdentification.CERTIDENTITY }
     * 
     */
    public SiteIdentification.CERTIDENTITY createSiteIdentificationCERTIDENTITY() {
        return new SiteIdentification.CERTIDENTITY();
    }

    /**
     * Create an instance of {@link MediaControl }
     * 
     */
    public MediaControl createMediaControl() {
        return new MediaControl();
    }

    /**
     * Create an instance of {@link Unicast }
     * 
     */
    public Unicast createUnicast() {
        return new Unicast();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Edl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EDL")
    public JAXBElement<Edl> createEDL(Edl value) {
        return new JAXBElement<Edl>(_EDL_QNAME, Edl.class, null, value);
    }

}
