//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ACCESS_CONTROL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DELIVERY_PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}SESSION_ADDITIONAL_PARAMS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SERVICE" minOccurs="0"/>
 *         &lt;element name="SCHEDULE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{}session-info"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "accesscontrol",
    "deliveryplatform",
    "sessionadditionalparams",
    "service",
    "schedule",
    "sessionInfo",
    "any"
})
@XmlRootElement(name = "SESSION")
public class SESSION {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "ACCESS_CONTROL")
    protected String accesscontrol;
    @XmlElement(name = "DELIVERY_PLATFORM", required = true, defaultValue = "Isabel")
    protected String deliveryplatform;
    @XmlElement(name = "SESSION_ADDITIONAL_PARAMS")
    protected List<SESSIONADDITIONALPARAMS> sessionadditionalparams;
    @XmlElement(name = "SERVICE")
    protected SERVICE service;
    @XmlElement(name = "SCHEDULE")
    protected Object schedule;
    @XmlElement(name = "session-info", required = true)
    protected SessionInfo sessionInfo;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the accesscontrol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCESSCONTROL() {
        return accesscontrol;
    }

    /**
     * Sets the value of the accesscontrol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCESSCONTROL(String value) {
        this.accesscontrol = value;
    }

    /**
     * Gets the value of the deliveryplatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVERYPLATFORM() {
        return deliveryplatform;
    }

    /**
     * Sets the value of the deliveryplatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVERYPLATFORM(String value) {
        this.deliveryplatform = value;
    }

    /**
     * Gets the value of the sessionadditionalparams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sessionadditionalparams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSESSIONADDITIONALPARAMS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SESSIONADDITIONALPARAMS }
     * 
     * 
     */
    public List<SESSIONADDITIONALPARAMS> getSESSIONADDITIONALPARAMS() {
        if (sessionadditionalparams == null) {
            sessionadditionalparams = new ArrayList<SESSIONADDITIONALPARAMS>();
        }
        return this.sessionadditionalparams;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link SERVICE }
     *     
     */
    public SERVICE getSERVICE() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link SERVICE }
     *     
     */
    public void setSERVICE(SERVICE value) {
    	//if there is a service there must be also ACCESS_CONTROL and DELIVERY_PLATFORM
    	if(value!=null)
    	{
    		if(getACCESSCONTROL()==null)
    		{
    			setACCESSCONTROL(null);
    		}
    		if(getDELIVERYPLATFORM()==null)
    		{
    			setDELIVERYPLATFORM("Isabel");
    		}
    	}
        this.service = value;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSCHEDULE() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSCHEDULE(Object value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the sessionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SessionInfo }
     *     
     */
    public SessionInfo getSessionInfo() {
        return sessionInfo;
    }

    /**
     * Sets the value of the sessionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionInfo }
     *     
     */
    public void setSessionInfo(SessionInfo value) {
        this.sessionInfo = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }
    
    public void setSERVICENAME(String myservice)
	{
		SERVICE servicio = this.getSERVICE();
		if(servicio==null)
			servicio = new SERVICE();
		servicio.setSERVICENAME(myservice);
		this.setSERVICE(servicio);
	}
	
	public void setSERVICEQUALITY(String myquality)
	{
		SERVICE servicio = this.getSERVICE();
		if(servicio==null)
			servicio = new SERVICE();
		servicio.setSERVICEQUALITY(myquality);
		this.setSERVICE(servicio);
	}
	
	public void setOPENSESSION(boolean isopen)
	{
		SessionInfo info_sess = this.getSessionInfo();
		if(info_sess==null)
			info_sess = new SessionInfo();
		info_sess.setOPENSESSION(isopen);
		this.setSessionInfo(info_sess);
	}
	
	public void setDESCRIPTION(String descrip)
	{
		SessionInfo info_sess = this.getSessionInfo();
		if(info_sess==null)
			info_sess = new SessionInfo();
		info_sess.setDESCRIPTION(descrip);
		this.setSessionInfo(info_sess);
	}
	
	
	public String getSERVICENAME()
	{
		String myservice;
		SERVICE servicio = this.getSERVICE();
		if(servicio==null)
			servicio = new SERVICE();
		myservice = servicio.getSERVICENAME();
		return myservice;
	}
	
	public String getSERVICEQUALITY()
	{
		String myquality;
		SERVICE servicio = this.getSERVICE();
		if(servicio==null)
			servicio = new SERVICE();
		myquality = servicio.getSERVICEQUALITY();
		return myquality;
	}
	
	public boolean getOPENSESSION()
	{
		boolean isopen;
		SessionInfo info_sess = this.getSessionInfo();
		isopen = info_sess.isOPENSESSION();
		return isopen;
	}
	
	public String getDESCRIPTION()
	{
		String descrip;
		SessionInfo info_sess = this.getSessionInfo();
		descrip = info_sess.getDESCRIPTION();
		return descrip;
	}
	
	
	/**
	 * method to add ONE comment, if you want to add more than one use addCOMMENT
	 * for every comment you want to add
	 * this method deletes the existing comments and adds a new one
	 * @param comentario the comment to add
	 */
	public void setCOMMENT(String comentario)
	{
		SessionInfo info_sess = this.getSessionInfo();
		if(info_sess==null)
			info_sess = new SessionInfo();	
		List comments = info_sess.getCOMMENT(); 
		comments.clear();
		comments.add(comentario);
		this.setSessionInfo(info_sess);
	}
	
	/**
	 * method to add more than one comment
	 * use this method once for every comment you want to add
	 * @param comentario the comment to add
	 */
	public void addCOMMENT(String comentario)
	{
		SessionInfo info_sess = this.getSessionInfo();
		if(info_sess==null)
			info_sess = new SessionInfo();
		List comments = info_sess.getCOMMENT();            		
		comments.add(comentario);
		this.setSessionInfo(info_sess);
	}

}
