//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ISABEL_ENABLE_VNC_MODE" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ISABEL_ENABLE_VMware_MODE" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ISABEL_DEFAULT_VNC_SERVER_DISPLAY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ISABEL_ISABEL_AUDIO_BYPASS_1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ISABEL_ISABEL_AUDIO_BYPASS_2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ISABEL_ISABEL_AUDIO_BYPASS_3" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IPSEC_ENABLE" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isabelenablevncmode",
    "isabelenablevMwareMODE",
    "isabeldefaultvncserverdisplay",
    "isabelisabelaudiobypass1",
    "isabelisabelaudiobypass2",
    "isabelisabelaudiobypass3",
    "ipsecenable",
    "any"
})
@XmlRootElement(name = "SESSION_ADDITIONAL_PARAMS")
public class SESSIONADDITIONALPARAMS {

    @XmlElement(name = "ISABEL_ENABLE_VNC_MODE")
    protected Boolean isabelenablevncmode;
    @XmlElement(name = "ISABEL_ENABLE_VMware_MODE")
    protected Boolean isabelenablevMwareMODE;
    @XmlElement(name = "ISABEL_DEFAULT_VNC_SERVER_DISPLAY")
    protected String isabeldefaultvncserverdisplay;
    @XmlElement(name = "ISABEL_ISABEL_AUDIO_BYPASS_1")
    protected Boolean isabelisabelaudiobypass1;
    @XmlElement(name = "ISABEL_ISABEL_AUDIO_BYPASS_2")
    protected Boolean isabelisabelaudiobypass2;
    @XmlElement(name = "ISABEL_ISABEL_AUDIO_BYPASS_3")
    protected Boolean isabelisabelaudiobypass3;
    @XmlElement(name = "IPSEC_ENABLE", defaultValue = "false")
    protected Boolean ipsecenable = false;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the isabelenablevncmode property.
     *   
     */
    public Boolean isISABELENABLEVNCMODE() {
        return isabelenablevncmode;
    }

    /**
     * Sets the value of the isabelenablevncmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISABELENABLEVNCMODE(boolean value) {
        this.isabelenablevncmode = value;
    }

    /**
     * Gets the value of the isabelenablevMwareMODE property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISABELENABLEVMwareMODE() {
        return isabelenablevMwareMODE;
    }

    /**
     * Sets the value of the isabelenablevMwareMODE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISABELENABLEVMwareMODE(Boolean value) {
        this.isabelenablevMwareMODE = value;
    }

    /**
     * Gets the value of the isabeldefaultvncserverdisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISABELDEFAULTVNCSERVERDISPLAY() {
        return isabeldefaultvncserverdisplay;
    }

    /**
     * Sets the value of the isabeldefaultvncserverdisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISABELDEFAULTVNCSERVERDISPLAY(String value) {
        this.isabeldefaultvncserverdisplay = value;
    }

    /**
     * Gets the value of the isabelisabelaudiobypass1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISABELISABELAUDIOBYPASS1() {
        return isabelisabelaudiobypass1;
    }

    /**
     * Sets the value of the isabelisabelaudiobypass1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISABELISABELAUDIOBYPASS1(Boolean value) {
        this.isabelisabelaudiobypass1 = value;
    }

    /**
     * Gets the value of the isabelisabelaudiobypass2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISABELISABELAUDIOBYPASS2() {
        return isabelisabelaudiobypass2;
    }

    /**
     * Sets the value of the isabelisabelaudiobypass2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISABELISABELAUDIOBYPASS2(Boolean value) {
        this.isabelisabelaudiobypass2 = value;
    }

    /**
     * Gets the value of the isabelisabelaudiobypass3 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISABELISABELAUDIOBYPASS3() {
        return isabelisabelaudiobypass3;
    }

    /**
     * Sets the value of the isabelisabelaudiobypass3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISABELISABELAUDIOBYPASS3(Boolean value) {
        this.isabelisabelaudiobypass3 = value;
    }

    /**
     * Gets the value of the ipsecenable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIPSECENABLE() {
        return ipsecenable;
    }

    /**
     * Sets the value of the ipsecenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIPSECENABLE(Boolean value) {
        this.ipsecenable = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
