//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ISABEL_VNC_SERVER_DISPLAY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ISABEL_GATEWAY" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ISABEL_AUDIOMIXER" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isabelvncserverdisplay",
    "isabelgateway",
    "isabelaudiomixer",
    "any"
})
@XmlRootElement(name = "SITE_ADDITIONAL_PARAMS")
public class SITEADDITIONALPARAMS {

    @XmlElement(name = "ISABEL_VNC_SERVER_DISPLAY")
    protected String isabelvncserverdisplay;
    @XmlElement(name = "ISABEL_GATEWAY")
    protected Object isabelgateway;
    @XmlElement(name = "ISABEL_AUDIOMIXER", defaultValue = "false")
    protected boolean isabelaudiomixer;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the isabelvncserverdisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISABELVNCSERVERDISPLAY() {
        return isabelvncserverdisplay;
    }

    /**
     * Sets the value of the isabelvncserverdisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISABELVNCSERVERDISPLAY(String value) {
        this.isabelvncserverdisplay = value;
    }

    /**
     * Gets the value of the isabelgateway property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getISABELGATEWAY() {
        return isabelgateway;
    }

    /**
     * Sets the value of the isabelgateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setISABELGATEWAY(Object value) {
        this.isabelgateway = value;
    }

    /**
     * Gets the value of the isabelaudiomixer property.
     * 
     */
    public boolean isISABELAUDIOMIXER() {
        return isabelaudiomixer;
    }

    /**
     * Sets the value of the isabelaudiomixer property.
     * 
     */
    public void setISABELAUDIOMIXER(boolean value) {
        this.isabelaudiomixer = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
