//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCESS_CONTROL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACCESS_CONTROL_TYPE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="CERT_IDENTITY" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="DN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FQDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PUBLIC_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SITE_ADDRESS" type="{}ipaddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ADMINISTRATIVE_INFORMATION" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="INSTITUTION" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="ADMINISTRATIVE_CONTACT" type="{}personal_information" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="TECHNICAL_CONTACT" type="{}personal_information" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "accesscontrol",
    "accesscontroltype",
    "certidentity",
    "userid",
    "publicname",
    "siteaddress",
    "administrativeinformation"
})
@XmlRootElement(name = "site-identification")
public class SiteIdentification {

    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "ACCESS_CONTROL")
    protected String accesscontrol;
    @XmlElement(name = "ACCESS_CONTROL_TYPE")
    protected Object accesscontroltype;
    @XmlElement(name = "CERT_IDENTITY")
    protected SiteIdentification.CERTIDENTITY certidentity;
    @XmlElement(name = "USER_ID")
    protected String userid;
    @XmlElement(name = "PUBLIC_NAME")
    protected String publicname;
    @XmlElement(name = "SITE_ADDRESS")
    protected List<String> siteaddress;
    @XmlElement(name = "ADMINISTRATIVE_INFORMATION")
    protected SiteIdentification.ADMINISTRATIVEINFORMATION administrativeinformation;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the accesscontrol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCESSCONTROL() {
        return accesscontrol;
    }

    /**
     * Sets the value of the accesscontrol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCESSCONTROL(String value) {
        this.accesscontrol = value;
    }

    /**
     * Gets the value of the accesscontroltype property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getACCESSCONTROLTYPE() {
        return accesscontroltype;
    }

    /**
     * Sets the value of the accesscontroltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setACCESSCONTROLTYPE(Object value) {
        this.accesscontroltype = value;
    }

    /**
     * Gets the value of the certidentity property.
     * 
     * @return
     *     possible object is
     *     {@link SiteIdentification.CERTIDENTITY }
     *     
     */
    public SiteIdentification.CERTIDENTITY getCERTIDENTITY() {
        return certidentity;
    }

    /**
     * Sets the value of the certidentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteIdentification.CERTIDENTITY }
     *     
     */
    public void setCERTIDENTITY(SiteIdentification.CERTIDENTITY value) {
        this.certidentity = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERID(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the publicname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUBLICNAME() {
        return publicname;
    }

    /**
     * Sets the value of the publicname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUBLICNAME(String value) {
        this.publicname = value;
    }

    /**
     * Gets the value of the siteaddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteaddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSITEADDRESS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSITEADDRESS() {
        if (siteaddress == null) {
            siteaddress = new ArrayList<String>();
        }
        return this.siteaddress;
    }

    /**
     * Gets the value of the administrativeinformation property.
     * 
     * @return
     *     possible object is
     *     {@link SiteIdentification.ADMINISTRATIVEINFORMATION }
     *     
     */
    public SiteIdentification.ADMINISTRATIVEINFORMATION getADMINISTRATIVEINFORMATION() {
        return administrativeinformation;
    }

    /**
     * Sets the value of the administrativeinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteIdentification.ADMINISTRATIVEINFORMATION }
     *     
     */
    public void setADMINISTRATIVEINFORMATION(SiteIdentification.ADMINISTRATIVEINFORMATION value) {
        this.administrativeinformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="INSTITUTION" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="ADMINISTRATIVE_CONTACT" type="{}personal_information" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="TECHNICAL_CONTACT" type="{}personal_information" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "institution",
        "administrativecontact",
        "technicalcontact",
        "url"
    })
    public static class ADMINISTRATIVEINFORMATION {

        @XmlElement(name = "DESCRIPTION")
        protected Object description;
        @XmlElement(name = "INSTITUTION")
        protected Object institution;
        @XmlElement(name = "ADMINISTRATIVE_CONTACT")
        protected List<PersonalInformation> administrativecontact;
        @XmlElement(name = "TECHNICAL_CONTACT")
        protected List<PersonalInformation> technicalcontact;
        @XmlElement(name = "URL")
        @XmlSchemaType(name = "anyURI")
        protected String url;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDESCRIPTION() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDESCRIPTION(Object value) {
            this.description = value;
        }

        /**
         * Gets the value of the institution property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getINSTITUTION() {
            return institution;
        }

        /**
         * Sets the value of the institution property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setINSTITUTION(Object value) {
            this.institution = value;
        }

        /**
         * Gets the value of the administrativecontact property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the administrativecontact property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getADMINISTRATIVECONTACT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonalInformation }
         * 
         * 
         */
        public List<PersonalInformation> getADMINISTRATIVECONTACT() {
            if (administrativecontact == null) {
                administrativecontact = new ArrayList<PersonalInformation>();
            }
            return this.administrativecontact;
        }

        /**
         * Gets the value of the technicalcontact property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the technicalcontact property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTECHNICALCONTACT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonalInformation }
         * 
         * 
         */
        public List<PersonalInformation> getTECHNICALCONTACT() {
            if (technicalcontact == null) {
                technicalcontact = new ArrayList<PersonalInformation>();
            }
            return this.technicalcontact;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getURL() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setURL(String value) {
            this.url = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="DN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FQDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dn",
        "fqdn"
    })
    public static class CERTIDENTITY {

        @XmlElement(name = "DN")
        protected String dn;
        @XmlElement(name = "FQDN")
        protected String fqdn;

        /**
         * Gets the value of the dn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDN() {
            return dn;
        }

        /**
         * Sets the value of the dn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDN(String value) {
            this.dn = value;
        }

        /**
         * Gets the value of the fqdn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFQDN() {
            return fqdn;
        }

        /**
         * Sets the value of the fqdn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFQDN(String value) {
            this.fqdn = value;
        }

    }

}
