//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.14 at 02:11:19 PM CET 
//


package xedl.lib.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UPBANDWIDTH" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DOWNBANDWIDTH" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "upbandwidth",
    "downbandwidth"
})
@XmlRootElement(name = "upanddownbandwidth")
public class Upanddownbandwidth {

    @XmlElement(name = "UPBANDWIDTH")
    protected int upbandwidth;
    @XmlElement(name = "DOWNBANDWIDTH")
    protected int downbandwidth;

    /**
     * Gets the value of the upbandwidth property.
     * 
     */
    public int getUPBANDWIDTH() {
        return upbandwidth;
    }

    /**
     * Sets the value of the upbandwidth property.
     * 
     */
    public void setUPBANDWIDTH(int value) {
        this.upbandwidth = value;
    }

    /**
     * Gets the value of the downbandwidth property.
     * 
     */
    public int getDOWNBANDWIDTH() {
        return downbandwidth;
    }

    /**
     * Sets the value of the downbandwidth property.
     * 
     */
    public void setDOWNBANDWIDTH(int value) {
        this.downbandwidth = value;
    }

}
