#!/bin/sh
########################################################################
#
#  ISABEL: A group collaboration tool for the Internet
#  Copyright (C) 2009 Agora System S.A.
#  
#  This file is part of Isabel.
#  
#  Isabel is free software: you can redistribute it and/or modify
#  it under the terms of the Affero GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Isabel is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  Affero GNU General Public License for more details.
# 
#  You should have received a copy of the Affero GNU General Public License
#  along with Isabel.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Esto estaba de comprobacion en Linux
# { if (NF != 5) next; }

case `uname`-`uname -r` in
    SunOS*)
    ipcrm `ipcs -m -o |
    awk '
	{ if ($7 != 0) next; }
	/^m/ { printf ("-m %s ", $2); }
    '
    ` >/dev/null 2>&1
    ;;
    IRIX*)
    ipcrm `ipcs -m -o |
    awk '
	{ if ($7 != 0) next; }
	/^m/ { printf ("-m %s ", $2); }
    '
    ` >/dev/null 2>&1
    ;;
    Linux*)
    lista=`ipcs -m |
    awk '
       { if ($6 != 0) next; }
       { printf ("%s ", $2); }
    '
    `
    for i in $lista ; do
	ipcrm shm $i >/dev/null 2>&1
    done
    ;;
esac
