include $(PROJECT_ROOT_DIR)/Makefile.head

# audio is required to compile the kal
# audio3 is required to compile the audio component

SUBDIRS.PRE= \
	sharedDisplay \
	video \
	irouter \
	wallpaper \
	titles \
	snmp \
	xutils \
	ftpOld \
	audio \
        sldFtp \
        speechMeter \
        lse \
        subtitles \
        question \
        seco \
        nereda

SUBDIRS.POST= \
	kernel \
	notepad \
	chat \
        gateway \
	whiteboard \
	license \
        MCU \
	vnc \
	scanner

include $(PROJECT_ROOT_DIR)/Makefile.tail
