#! /bin/sh
########################################################################
#
#  ISABEL: A group collaboration tool for the Internet
#  Copyright (C) 2009 Agora System S.A.
#  
#  This file is part of Isabel.
#  
#  Isabel is free software: you can redistribute it and/or modify
#  it under the terms of the Affero GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Isabel is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  Affero GNU General Public License for more details.
# 
#  You should have received a copy of the Affero GNU General Public License
#  along with Isabel.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

#-----------------------------------------------------
# isabel directory.
#-----------------------------------------------------
if [ -z "$ISABEL_DIR" ] ; then
  ISABEL_DIR=/usr/local/isabel
  export ISABEL_DIR
fi

#-----------------------------------------------------
# isabel common code
#-----------------------------------------------------
. $ISABEL_DIR/bin/isabel.common.sh


#-----------------------------------------------------
# isabel environment variables
#-----------------------------------------------------
. $ISABEL_DIR/bin/isabel.environ.sh

XMLRPCJARS=$ISABEL_DIR/libexec/xmlrpc/commons-logging-1.1.jar:$ISABEL_DIR/libexec/xmlrpc/ws-commons-util-1.0.2.jar:$ISABEL_DIR/libexec/xmlrpc/xmlrpc-client-3.1.jar:$ISABEL_DIR/libexec/xmlrpc/xmlrpc-common-3.1.jar:$ISABEL_DIR/libexec/xmlrpc/xmlrpc-server-3.1.jar

java -cp $XMLRPCJARS:/usr/local/isabel/libexec/xlim_lib.jar:/usr/local/isabel/libexec/isabel_xlimservices.jar:/usr/local/isabel/libexec/xedl.jar:/usr/local/isabel/libexec/xerl.jar:/usr/local/isabel/libexec/xedlsplitter.jar:/usr/local/isabel/libexec/isabel_xlim.jar:/usr/local/isabel/lib/images/xlim/:/usr/local/isabel/libexec/isabel_lib.jar  -Dprior.config.file=/usr/local/isabel/lib/xlimconfig/priorxedl.cfg  -Disabel.dir=$ISABEL_DIR/ -Disabel.profiles.dir=$ISABEL_PROFILES_DIR -Disabel.sessions.dir=$ISABEL_SESSIONS_DIR -Disabel.user.dir=$ISABEL_USER_DIR -Disabel.config.dir=$ISABEL_CONFIG_DIR  services/isabel/services/isabellauncher/SessionManager $1
