/*
 * ISABEL: A group collaboration tool for the Internet
 * Copyright (C) 2009 Agora System S.A.
 * 
 * This file is part of Isabel.
 * 
 * Isabel is free software: you can redistribute it and/or modify
 * it under the terms of the Affero GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Isabel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Affero GNU General Public License for more details.
 * 
 * You should have received a copy of the Affero GNU General Public License
 * along with Isabel.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * ErrorPanel2.java
 *
 * Created on 19 de mayo de 2004, 16:14
 */

package services.isabel.lib;

import java.awt.*;

/**
 *
 * @author  lailoken
 */
public class ErrorPanel extends javax.swing.JPanel {
  
  /** Creates new form ErrorPanel2 */
  public ErrorPanel() {
    initComponents();
  }

  /**
   * Devuelve el campo ServerContent.
   */
  public String getServerContentLabel() {
    return serverContent.getText();
  }
    

  /**
   * Devuelve el campo ServiceContent.
   */
  public String getServiceContentLabel() {
    return serviceContent.getText();
  }
    
  /**
   * Devuelve el campo ErrorContent.
   */
  public String getErrorContentLabel() {
    return errorContent.getText();
  }

  
  /**
   * Establece el campo ServerContent
   */    
  public void setServerContentLabel(String text) {
    serverContent.setText(text);
  }
    
  /**
   * Establece el campo ServiceContent
   */    
  public void setServiceContentLabel(String text) {
    serviceContent.setText(text);
  }

  /**
   * Establece el campo ErrorContent
   */    
  public void setErrorContentLabel(String text) {
    errorContent.setText(text);
  }
  
  /**
   * Establece el campo ErrorTextArea
   */    
  public void setErrorTextArea(String text) {
    errorTextArea.append(text);
  }
  
  
  public void setTextAreaDimension() {
    // Ajustamos la dimension del scrollPanel a la del panel que lo contiene:
    double serverHeight = serverPanel.getPreferredSize().getHeight();
    double serverWidth = serverPanel.getPreferredSize().getWidth();
    double errorHeight = errorPanel.getPreferredSize().getHeight();
    double errorWidth = errorPanel.getPreferredSize().getWidth();
    double errorTextHeight = errorTextPanel.getPreferredSize().getHeight();
    double errorTextWidth = errorTextPanel.getPreferredSize().getWidth();
    Dimension newDimension = new Dimension();
    newDimension.setSize(serverWidth, errorHeight);
    errorPanel.setPreferredSize(newDimension);
    Dimension newTextDimension = new Dimension();
    newTextDimension.setSize(serverWidth, errorTextHeight);
    errorTextPanel.setPreferredSize(newTextDimension);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    serverPanel = new javax.swing.JPanel();
    serviceContent = new javax.swing.JLabel();
    serverLabel = new javax.swing.JLabel();
    serviceLabel = new javax.swing.JLabel();
    serverContent = new javax.swing.JLabel();
    introLabel = new javax.swing.JLabel();
    errrorLabel = new javax.swing.JLabel();
    errorContent = new javax.swing.JLabel();
    errorPanel = new javax.swing.JPanel();
    errorDetailsLabel = new javax.swing.JLabel();
    errorTextPanel = new javax.swing.JScrollPane();
    errorTextArea = new javax.swing.JTextArea();

    setLayout(new java.awt.GridBagLayout());

    serverPanel.setLayout(new java.awt.GridBagLayout());

    serviceContent.setText("ServiceC");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
    serverPanel.add(serviceContent, gridBagConstraints);

    serverLabel.setText("Server:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 20, 0, 11);
    serverPanel.add(serverLabel, gridBagConstraints);

    serviceLabel.setText("Service:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 20, 0, 11);
    serverPanel.add(serviceLabel, gridBagConstraints);

    serverContent.setText("ServerC");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
    serverPanel.add(serverContent, gridBagConstraints);

    introLabel.setText("Received an error message from");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    serverPanel.add(introLabel, gridBagConstraints);

    errrorLabel.setText("Error:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.ipadx = 5;
    gridBagConstraints.ipady = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 20, 0, 11);
    serverPanel.add(errrorLabel, gridBagConstraints);

    errorContent.setText("ErrorC");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
    serverPanel.add(errorContent, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.ipadx = 5;
    gridBagConstraints.ipady = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    //serverPanel.setBackground(Color.CYAN);
    BorderLayout border = new BorderLayout();
    setLayout(border);
    add(serverPanel, BorderLayout.NORTH);

    errorPanel.setLayout(new java.awt.BorderLayout());

    errorDetailsLabel.setText("Error Details:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    errorPanel.add(errorDetailsLabel, BorderLayout.NORTH);

    errorTextArea.setColumns(40);
    errorTextArea.setEditable(false);
    errorTextArea.setFont(new java.awt.Font("MonoSpaced", 0, 10));
    errorTextArea.setLineWrap(true);
    errorTextArea.setRows(5);
    errorTextArea.setWrapStyleWord(true);
    errorTextArea.setMargin(new java.awt.Insets(3, 3, 3, 3));
    errorTextArea.setMaximumSize(new java.awt.Dimension(300, 300));
    //errorTextArea.setBackground(Color.YELLOW);
    errorTextPanel.setViewportView(errorTextArea);

    //errorTextPanel.setBackground(Color.RED);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    errorPanel.add(errorTextPanel, BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.ipadx = 5;
    gridBagConstraints.ipady = 7;
    gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
    gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
    //errorPanel.setBackground(Color.ORANGE);
    add(errorPanel, BorderLayout.CENTER);

  }
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel errorContent;
  private javax.swing.JLabel errorDetailsLabel;
  private javax.swing.JPanel errorPanel;
  private javax.swing.JTextArea errorTextArea;
  private javax.swing.JScrollPane errorTextPanel;
  private javax.swing.JLabel errrorLabel;
  private javax.swing.JLabel introLabel;
  private javax.swing.JLabel serverContent;
  private javax.swing.JLabel serverLabel;
  private javax.swing.JPanel serverPanel;
  private javax.swing.JLabel serviceContent;
  private javax.swing.JLabel serviceLabel;
  // End of variables declaration//GEN-END:variables
  
}
