/*
 * ISABEL: A group collaboration tool for the Internet
 * Copyright (C) 2009 Agora System S.A.
 * 
 * This file is part of Isabel.
 * 
 * Isabel is free software: you can redistribute it and/or modify
 * it under the terms of the Affero GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Isabel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Affero GNU General Public License for more details.
 * 
 * You should have received a copy of the Affero GNU General Public License
 * along with Isabel.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * StatusFrame.java
 *
 * Created on 1 de octubre de 2004, 13:12
 */

package services.isabel.lib;

import java.io.*;

/**
 *
 * @author  lailoken
 */
public class StatusFrame extends javax.swing.JFrame {
  

  
  /** Creates new form StatusFrame */
  public StatusFrame() {
    initComponents();
    setTitle("ISABEL Connect To Status");
    setMsg("    Processing...    ",0);
    show();
  }

  public StatusFrame(String title, String msg) {
    initComponents();
    setTitle(title);
    setMsg(msg,0);
    show();
  }

  /**
   * Oculta el panel
   */
  public void hideStatusWindow() {
    //frame.setVisible(false);
    //System.out.println("Hiding..");
    hide();
    dispose();
  }


  /**
   * Establece un nuevo mensaje para ense�ar en el panel
   */
  public void setMsg(String newMsg,int newValue) {
    textArea.append(newMsg + "\r\n");
    progressBar.setIndeterminate(false);
    progressBar.setValue(newValue);
    pack();
    show();
  }
    
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    java.awt.GridBagConstraints gridBagConstraints;

    textScrollPanel = new javax.swing.JScrollPane();
    textArea = new javax.swing.JTextArea();
    progressBar = new javax.swing.JProgressBar();
    cancelButton = new javax.swing.JButton();

    getContentPane().setLayout(new java.awt.GridBagLayout());

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    textArea.setColumns(40);
    textArea.setEditable(false);
    textArea.setFont(new java.awt.Font("MonoSpaced", 0, 10));
    textArea.setLineWrap(true);
    textArea.setRows(5);
    textArea.setWrapStyleWord(true);
    textArea.setMargin(new java.awt.Insets(3, 3, 3, 3));
    textArea.setMaximumSize(new java.awt.Dimension(300, 300));
    
    textScrollPanel.setBorder(new javax.swing.border.EtchedBorder());
    textScrollPanel.setMaximumSize(new java.awt.Dimension(100, 50));
    textScrollPanel.setMinimumSize(new java.awt.Dimension(100, 50));
    textScrollPanel.setPreferredSize(new java.awt.Dimension(250, 120));
    textScrollPanel.setAutoscrolls(true);
    textScrollPanel.setViewportView(textArea);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 1, 5);
    gridBagConstraints.weightx = 1;
    gridBagConstraints.weighty = 1;
    getContentPane().add(textScrollPanel, gridBagConstraints);

    progressBar.setIndeterminate(true);
    progressBar.setStringPainted(true);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(1, 5, 5, 5);
    getContentPane().add(progressBar, gridBagConstraints);

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    getContentPane().add(cancelButton, gridBagConstraints);

    pack();
  }//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    System.exit(0);
  }//GEN-LAST:event_cancelButtonActionPerformed
  
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit(0);
  }//GEN-LAST:event_exitForm
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    StatusFrame sf = new StatusFrame("Connect To Status","Processing...  ");
    //StatusFrame sf = new StatusFrame();
    //PrintWriter outMsgFile = null;
    //Servutilities.writeStatusMsg("kk",3,sf, outMsgFile,true);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JProgressBar progressBar;
  private javax.swing.JTextArea textArea;
  private javax.swing.JScrollPane textScrollPanel;
  // End of variables declaration//GEN-END:variables
  
}
