#! /bin/sh

#
# Check variables
#
if [ -z "$SRC_DIR" ] ; then echo "SRC_DIR undefined" ; exit ; fi
if [ -z "$PKG_NAME" ] ; then echo "PKG_NAME undefined" ; exit ; fi
if [ -z "$DISTRIB_DIR" ] ; then echo "DISTRIB_DIR undefined" ; exit ; fi
if [ -z "$PKG_DIR" ] ; then echo "PKG_DIR undefined" ; exit ; fi

# Directorio de instalacion (relativo):
export ISA_RELDIR="usr/local/isabeldevel"

#
# Clean start up
#
sudo rm -rf $PKG_DIR

#
# Copy files to build the package
#
(cd $SRC_DIR/admin/pkg.$PKG_NAME/ ; ./mkPkg_copy.sh)


VERSIONS_DIR=$ISA_VERSIONS_DIR/$PKG_NAME
if [ ! -d $VERSIONS_DIR ] ; then 
    mkdir -p $VERSIONS_DIR
fi 

#
# Hacer el paquete y copiar en el directorio de versiones.
#
if [ "$PKG_TYPE" = "rpm" ] ; then

   ./mkPkg_rpm.sh

   RPMFILENAME=$PKG_NAME-$VERSION-$RELEASE.i586.rpm
   mv $RPM_DIR/$RPMFILENAME $VERSIONS_DIR
   chmod 644 $VERSIONS_DIR/$RPMFILENAME
   rm -rf $PKG_DIR

elif [ "$PKG_TYPE" = "deb" ] ; then

   export DEBFILENAME=$(echo ${PKG_NAME}_${VERSION}-${RELEASE}_${LINUX_DISTRIB}_i586.deb | tr A-Z a-z)
   ./mkPkg_deb.sh

   mv $DEB_DIR/$DEBFILENAME $VERSIONS_DIR
   chmod 644 $VERSIONS_DIR/$DEBFILENAME
   sudo rm -rf $PKG_DIR

fi

exit 0


