include $(PROJECT_ROOT_DIR)/Makefile.head

distrib::
	@echo "isabel_scanner --> $(DISTRIB_DIR)/isabelcore/bin"
	@mkdir -p $(DISTRIB_DIR)/isabelcore/bin
	@cp -f ./isabel_scanner $(DISTRIB_DIR)/isabelcore/bin
	@chmod a+x $(DISTRIB_DIR)/isabelcore/bin/isabel_scanner


include $(PROJECT_ROOT_DIR)/Makefile.tail
