include $(PROJECT_ROOT_DIR)/Makefile.head

SUBDIRS.PRE=
SUBDIRS.POST=

distrib::
	@mkdir -p $(DISTRIB_DIR)/isabelcore/bin
	@cp install_alternatives $(DISTRIB_DIR)/isabelcore/bin
	@cp stop_services  $(DISTRIB_DIR)/isabelcore/bin


include $(PROJECT_ROOT_DIR)/Makefile.tail
