include $(PROJECT_ROOT_DIR)/Makefile.head

SUBDIRS.PRE=gpl register
SUBDIRS.POST=

distrib::
	@mkdir -p $(DISTRIB_DIR)/isabelcore/doc
	@cp -f doc/ASSA-LICENSE.txt $(DISTRIB_DIR)/isabelcore/doc/.

include $(PROJECT_ROOT_DIR)/Makefile.tail
